### PR TITLE
Feature/responsive cart

### PR DESCRIPTION
**Pull request by swati-maheshwari**
Webp net-gifmaker (2)

### CODE REVIEW

**Comment by swati-maheshwari** [comment]
@shreyanshp @li-zheng-paypay @stefan-pp Please review.. I am not able to add reviewers therefore commenting..thank you.

**Review by shreyanshp — APPROVED** [review]

**Comment by shreyanshp** [comment]
LGTM @swati-maheshwari , thank you for the PR!
Added the app-sdk team to the repo!

**Review by li-zheng-paypay — APPROVED** [review]
What's the break point of this page?

**Review by stefan-pp — APPROVED** [review]

**Comment by swati-maheshwari** [comment]
> What's the break point of this page?

>245px width

**Review by solancer — APPROVED** [review]
LGTM

**Pull request merged**
